version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  api:
    build: ./backend
    container_name: api
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      # - /dev/snd:/dev/snd
    privileged: true
    # network_mode: host
    extra_hosts:
      # - "host.docker.internal:host-gateway"
      - "${HA_IP_ADDRESS}:host-gateway"
    # devices:
    #   - /dev/snd:/dev/snd
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
