version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - example.env # Change to .env and add your own credentials
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3

  backend:
    build: ./backend
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
